---
- name: Setting Up K8s
  hosts: all
  tasks:
    - name: Starting Docker
      shell: open -a Docker
    - name: Starting minikube
      shell: minikube start
    - name: Adding minikube addons ingress
      shell: minikube addons enable ingress
    - name: Minikube Tunneling
      shell: minikube tunnel &
    - name: checking contents
      shell: cd kubernetesnew
