# ---
# # Define a 'Service' To Expose the application
# apiVersion: v1
# kind: Service
# metadata:
#   name: prometheus-grafana
# spec:
#   ports:
#     - protocol: "TCP"
#       port: 80    # Port inside the cluster
#       targetPort: 80  # Port exposed to the outside
#       # nodePort: 30100
#   selector:
#     app: react
#   type: ClusterIP
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: grafana
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /$1
# spec:
#   rules:
#   - host: "Monitoring.com"
#     http:
#       paths:
#       - pathType: Prefix
#         path: "/monitoring/(.*)"
#         backend:
#           service:
#             name: 
#             port:
#               number: 3000